apiVersion: v1
kind: Service
metadata:
  name: master
spec:
  selector:
    app: master
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: batch/v1
kind: Job
metadata:
  name: master
spec:
  template:
    metadata:
      labels:
        app: master
    spec:
      restartPolicy: Never
      containers:
      - name: distributed-tests-prototype
        image: advancedtelematic/distributed-tests-prototype:latest
        args: ["master", $(IP)]
        env:
          - name: IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: batch/v1
kind: Job
metadata:
  name: slave
spec:
  parallelism: 2
  template:
    metadata:
      name: slave
    spec:
      restartPolicy: Never
      containers:
      - name: distributed-tests-prototype
        image: advancedtelematic/distributed-tests-prototype:latest
        args: ["slave", $(IP), "8080"]
        env:
          - name: IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
      initContainers:
        - name: init-slave
          image: busybox
          command: ['sh', '-c', 'until nc -z master 8080; do sleep 1; done;']
