name:                distributed-tests-prototype
version:             0.1.0.0
github:              "advancedtelematic/distributed-tests-prototype"
license:             BSD2
author:              "Stevan Andjelkovic"
maintainer:          "stevan.andjelkovic@here.com"
copyright:           "Copyright (C) 2018, HERE Europe B.V."

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Testing

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/advancedtelematic/distributed-tests-prototype#readme>

dependencies:
- base >= 4.7 && < 5
- binary
- containers
- distributed-process
- mtl
- network-transport
- network-transport-tcp
- pretty-show
- random
- QuickCheck
- stm
- strict
- tasty-hunit

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  distributed-tests-prototype:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - distributed-tests-prototype

tests:
  distributed-tests-prototype-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - distributed-tests-prototype
    - tasty
    - tasty-discover
    - tasty-hunit
    - tasty-quickcheck
    - strict
