name:                quickcheck-state-machine-distributed
version:             0.1.0.0
github:              "advancedtelematic/quickcheck-state-machine-distributed"
license:             BSD2
author:              "Stevan Andjelkovic"
maintainer:          "stevan.andjelkovic@here.com"
copyright:           "Copyright (C) 2018, HERE Europe B.V."

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Test monadic programs using state machine based models
category:            Testing

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/advancedtelematic/quickcheck-state-machine-distributed#readme>

dependencies:
- base >= 4.7 && < 5
- binary
- containers
- distributed-process >= 0.7.3
- mtl
- network-transport >= 0.5.2
- network-transport-tcp >= 0.6.0
- random
- QuickCheck >= 2.11.3
- stm

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  source-dirs: src

tests:
  quickcheck-state-machine-distributed-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - directory
    - quickcheck-state-machine-distributed
    - strict
    - tasty
    - tasty-quickcheck
    - temporary 
